# Generated by Django 5.0.1 on 2024-01-15 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Char',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OptionChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Selection.char')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Selection.option')),
            ],
            options={
                'verbose_name': 'Option char',
                'verbose_name_plural': 'Option chars ',
            },
        ),
        migrations.AddField(
            model_name='char',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Selection.selection'),
        ),
    ]
